//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC4_Launcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string steam_path {
            get {
                return ((string)(this["steam_path"]));
            }
            set {
                this["steam_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int steam_id {
            get {
                return ((int)(this["steam_id"]));
            }
            set {
                this["steam_id"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sc4_mapper_on {
            get {
                return ((bool)(this["sc4_mapper_on"]));
            }
            set {
                this["sc4_mapper_on"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sc4_mapper_path {
            get {
                return ((string)(this["sc4_mapper_path"]));
            }
            set {
                this["sc4_mapper_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
=======
        [global::System.Configuration.DefaultSettingValueAttribute("+")]
>>>>>>> 9a098a6572d6421af8f5fdf106fe0a7ce6e7440f
        public char alt_key_end {
            get {
                return ((char)(this["alt_key_end"]));
            }
            set {
                this["alt_key_end"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
<<<<<<< HEAD
=======
        [global::System.Configuration.DefaultSettingValueAttribute("#")]
>>>>>>> 9a098a6572d6421af8f5fdf106fe0a7ce6e7440f
        public char alt_key_pos1 {
            get {
                return ((char)(this["alt_key_pos1"]));
            }
            set {
                this["alt_key_pos1"] = value;
            }
        }
    }
}
